# Generated by Django 4.1.1 on 2023-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('goal', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
