# Generated by Django 4.1.1 on 2023-04-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_dietenquiry_contact_phone_alter_enquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Banner/')),
            ],
        ),
    ]
